# Generated by Django 5.1.3 on 2024-11-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banqueteria',
            name='link_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='componentebanqueteria',
            name='link_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='link_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
