# Generated by Django 5.1.3 on 2024-11-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_banqueteria_link_img_componentebanqueteria_link_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('link_img', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='banqueteria',
            name='componentes',
        ),
        migrations.AddField(
            model_name='banqueteria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='id_componenetes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.componente'),
        ),
        migrations.DeleteModel(
            name='ComponenteBanqueteria',
        ),
    ]
