# Generated by Django 5.1.3 on 2024-11-26 07:39

from django.db import migrations

def cargar_datos(apps, schema_editor):
    cliente = apps.get_model('usuario', 'cliente')  # Ajusta nombre_app y NombreModelo
    cliente.objects.create(rut='12345678-9', nombre='Juan', apellido1='Perez', nickname= 'user1', telefono='12345678', correo= 'prueba@gmail.com', password= '12345')

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_datos),
    ]
