# Generated by Django 5.1.3 on 2024-11-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
    ]
