# Generated by Django 5.1.3 on 2024-11-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20241126_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido1',
            new_name='apellido',
        ),
    ]
