# Generated by Django 5.1.3 on 2024-11-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente_banqueteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Banqueteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('componentes', models.ManyToManyField(to='evento.componente_banqueteria')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_personas', models.IntegerField()),
                ('fecha_evento', models.DateField()),
                ('id_banqueteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.banqueteria')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('id_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.local')),
            ],
        ),
    ]
