# Generated by Django 5.1.3 on 2024-11-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componente_banqueteria',
            new_name='ComponenteBanqueteria',
        ),
    ]
