# Generated by Django 5.1.3 on 2024-11-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salones_arrendados', models.IntegerField()),
                ('banqueteria_vendidas', models.IntegerField()),
                ('mes', models.CharField(max_length=100)),
                ('total_mensual', models.IntegerField()),
                ('cancelaciones', models.CharField(max_length=100)),
            ],
        ),
    ]
